### ISSUE TITLE
No drag cropping does not work

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [SmartToolFactory/Compose-Cropper#15]
When I don't drag the crop, for example, I select 1:1 square and then click crop directly, the resulting image is the original rectangle without the crop. If I move the image or crop box slightly, it works fine. demo can also reproduce this problem.

**Comment by jlasic** [comment]
+1 I'm experiancing the same issue

**Comment by SmartToolFactory** [comment]
Would you mind testing with version 0.3.0, i don't get this issue but if you still do i will check it out this weekend hopefully.

**Comment by jlasic** [comment]
It's fixed for my case, static cropping

**Comment by DSrhoj** [comment]
This issue is still persistent for me.
I reproduced it from demo like [AndroidJohnsonWang](https://github.com/AndroidJohnsonWang) wrote in his comment.
I also reproduced it with the following configuration in my project:

CropDefaults.properties(
                cropOutlineProperty = CropOutlineProperty(
                    OutlineType.Rect,
                    RectCropShape(0, "Rect")
                ),
                contentScale = ContentScale.Fit,
                aspectRatio = AspectRatio(1f),
                overlayRatio = 1f,
                cropType = CropType.Static,
                handleSize = 0f
            )

I reproduced it in demo by replacing lines 72-78 of file "ImageCropDemo.kt" with configuration provided above.
Cropping without any actions returns whole image instead of 1:1 rectangle portion of image.
I tried 0.3.0 and 0.3.4 versions in my project with the same result.
